Add basic k8s components
JupiterOne/graph-kubernetes pull request #1
Opened 2021-05-10 19:56 UTC by eXtremeX

(_I will update this description tomorrow_)

cc @austinkelleher

2021-05-13 12:17 UTC, austinkelleher requested changes
This is looking excellent! Posting some initial feedback as I go. Still working through this one! Thanks a lot for the hard work! 🥳

2021-05-13 12:17 UTC, austinkelleher commented on src/steps/pods/__snapshots__/converters.test.ts.snap
> +          "serviceAccount": "default",
Out of scope of PR - We should consider creating entities for service accounts and build `USES` relationships.

2021-05-13 12:17 UTC, austinkelleher commented on src/steps/pods/index.ts
> +            if (!(await jobState.findEntity(getContainerKey(container.name)))) {
Thanks for being careful here. I assume this is to prevent duplicate container entities? `jobState.findEntity` is fairly fast, but it requires reading from the file system and parsing the file where this entity is stored. If there are many containers in the cluster, we may end up spending quite a bit of time in I/O using `findEntity`. We could speed this step up quite a bit by using an in-memory `Set<string>` to prevent duplicates.

Example:

```ts
const containerEntityKeys = new Set<string>();

...

const containerEntityKey = getContainerKey(container.name);

if (!containerEntityKeys.has(containerEntityKey)) {
  await jobState.addEntity(containerEntity);
  containerEntityKeys.add(containerEntityKey);
  ...
}
```

2021-05-13 12:17 UTC, austinkelleher commented on src/steps/pods/index.ts
> +          const nodeUid = (await jobState.getData(
`getData` takes a generic. Instead of casting, you can do:

```ts
await jobState.getData<string>(`node:${pod.spec?.nodeName}`);
```

Additionally, I've tried to co-locate the setter and getter for the `jobState` data in utility files, so that it's very clear which key to use. How about something like:

**src/util/jobState.ts**
```ts
function getNodeCacheKeyFromPod(pod: Pod) {
  return `node:${pod.spec?.nodeName}`;
}

export function cachePodNodeNameToUid(jobState: JobState) {

}

export function getPodUidByNodeName(jobState: JobState, pod: Pod) {
  
}
```

Additionally, I wonder if it's possible that in between the time that we set the initial data, and the time that we use the data, that the cluster has changed. Perhaps there are _new_ nodes that did not exist at the time we called `jobState.setData`. If that is possible, we should make sure to handle the case that there was no result returned back, and simply skip `jobState.findEntity` (small optimization).

2021-05-13 12:17 UTC, austinkelleher commented on src/steps/pods/index.ts
> +            `node:${pod.spec?.nodeName}`,
Is it actually possible for `nodeName` to be `undefined`? Should we skip the lookup if it is?

2021-05-13 13:35 UTC, eXtremeX commented on configs/createSecret.yml
> +  name: jone-secret
Sounds good!

2021-05-13 13:42 UTC, eXtremeX commented on src/kubernetes/clients/core.ts
> +  // TODO: to be replaced with most lightweight API call
A bit, like, I'm still not sure if this is the **most** lightweight API call, but considering namespaces are very top-level resources (and fewer in comparison to say, nodes/pods/services/etc) it should be among the ones.

2021-05-13 13:45 UTC, eXtremeX commented on src/steps/replica-sets/__snapshots__/converters.test.ts.snap
> +          "labels": Object {
Yes, I'm afraid this requires more research. Was initially thinking of adding something similar to GCP like you suggested, but we need to make sure labels don't play a more important role here than they did in GCP.

Perhaps this is a good topic after this PR gets merged?

2021-05-13 13:46 UTC, eXtremeX commented on src/steps/deployments/converters.ts
> +        // TODO: these seem to be strings in my example, but TS type tells they're objects
That's a good idea, we can try doing something like that!

2021-05-13 13:46 UTC, eXtremeX commented on src/steps/pods/__snapshots__/converters.test.ts.snap
> +          "serviceAccount": "default",
We should note down these ideas somewhere! Agree, sounds good!

2021-05-13 13:58 UTC, austinkelleher commented on src/kubernetes/clients/authorization.ts
> +    const resp = await this.client.createSelfSubjectAccessReview({
This seems like something we should consider ingesting as entities later

2021-05-13 13:58 UTC, austinkelleher commented on src/steps/constants.ts
> +    _class: ['Group'],
I'm wondering if we should change this to a `Task`.

https://github.com/JupiterOne/data-model/blob/master/src/schemas/Task.json#L4

> A computational task. Examples include AWS Batch Job, ECS Task, etc.

From the [K8S Pod documentation](https://kubernetes.io/docs/concepts/workloads/pods/):

> Pods are the smallest deployable units of computing that you can create and manage in Kubernetes.

2021-05-13 13:58 UTC, austinkelleher commented on src/steps/constants.ts
> +    _class: ['Container'],
Reading the `data-model` for `Workload` and wondering if we should switch this one:

https://github.com/JupiterOne/data-model/blob/master/src/schemas/Workload.json#L4

> A virtual compute instance, it could be an aws-ec2-instance, a docker-container, an aws-lambda-function, an application-process, or a vmware-instance. The exact workload type is described in the _type property of the Entity.

2021-05-13 13:58 UTC, austinkelleher commented on src/steps/constants.ts
> +    _class: ['Container'],
`Container` does seem more natural though. Here are the docs for `Container`:

https://github.com/JupiterOne/data-model/blob/master/src/schemas/Container.json

> A standard unit of software that packages up code and all its dependencies and configurations.

2021-05-13 13:58 UTC, austinkelleher commented on src/steps/constants.ts
> +    _class: ['Group'],
Trying to think if there is a more natural `_class` for `kube_node`. It almost feels like a `Workload` when reading the documentation...

https://kubernetes.io/docs/concepts/architecture/nodes/

> Kubernetes runs your workload by placing containers into Pods to run on Nodes. A node may be a virtual or physical machine, depending on the cluster. Each node is managed by the control plane and contains the services necessary to run Pods

https://github.com/JupiterOne/data-model/blob/master/src/schemas/Workload.json#L4

> A virtual compute instance, it could be an aws-ec2-instance, a docker-container, an aws-lambda-function, an application-process, or a vmware-instance. The exact workload type is described in the _type property of the Entity.

2021-05-13 13:58 UTC, austinkelleher commented on src/steps/constants.ts
> +    _class: ['Configuration'],
This is a really interesting doc that _kind of_ describes ReplicaSets as deployments (a bit confusing):

https://kubernetes.io/docs/concepts/workloads/


> Kubernetes provides several built-in workload resources:
>
> - Deployment and ReplicaSet (replacing the legacy resource ReplicationController). Deployment is a good fit for managing a stateless application workload on your cluster, where any Pod in the Deployment is interchangeable and can be replaced if needed.

2021-05-13 13:58 UTC, austinkelleher commented on src/steps/constants.ts
> +    _class: ['Configuration'],
See below comment about workloads

2021-05-14 15:17 UTC, eXtremeX commented on src/steps/pods/index.ts
> +            `node:${pod.spec?.nodeName}`,
It can, `nodeName?: string;`, that's a good idea! :+1:

2021-05-14 15:19 UTC, eXtremeX commented on src/steps/constants.ts
> +    _class: ['Group'],
:+1: Even if we later find some class that suits it better, `Task` is much better than the current `Group` so I'll change it!

2021-05-14 15:24 UTC, eXtremeX commented on src/steps/constants.ts
> +    _class: ['Configuration'],
They're very tightly coupled for sure. But these pages [Deployment](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/), [ReplicaSet](https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/) both have 2 YAML file examples where they have different kinds: Deployment and ReplicaSet.

**ReplicaSet**

> A ReplicaSet's purpose is to maintain a stable set of replica Pods running at any given time. As such, it is often used to guarantee the availability of a specified number of identical Pods.

**Deployments**

> A Deployment provides declarative updates for Pods and ReplicaSets.
> 
> You describe a desired state in a Deployment, and the Deployment Controller changes the actual state to the desired state at a controlled rate. You can define Deployments to create new ReplicaSets, or to remove existing Deployments and adopt all their resources with new Deployments.

2021-05-14 15:27 UTC, eXtremeX commented on src/steps/constants.ts
> +    _class: ['Configuration'],
Do you think we should tag `kube_deployment` and `kube_replicaset` as Workloads? I'm split because it depends on how you look at it, one way of looking could be that deployments and replicasets are configs that describe the desired state and then k8s controllers act upon that and spawn/maintain the pods within the nodes (<- where they can be seen as Workloads, Tasks and so on instead). But I'm not sure if this correct way of looking at it either.

2021-05-14 15:29 UTC, eXtremeX commented on src/steps/constants.ts
> +    _class: ['Container'],
Hmm, it seems both could work.

> Kubernetes supports several container runtimes: Docker, containerd, CRI-O, and any implementation of the Kubernetes CRI (Container Runtime Interface).

2021-05-14 15:34 UTC, eXtremeX commented on src/steps/constants.ts
> +    _class: ['Group'],
Hmm, `Group` definitely feels almost too generic. The `Workload` does share some similarities with the Kubernetes description. The only problem is `kube_node` feels wider than the Workload if Workload description mentions docker-container, aws-ec2-instance.. e.g. `kube_node` has a lot of `kube_pod`s which in turn have a lot of `kube_container`s (which we may want to classify as Workloads).

2021-05-17 15:19 UTC, eXtremeX commented on src/steps/pods/index.ts
> +            if (!(await jobState.findEntity(getContainerKey(container.name)))) {
We had a chat about this over Slack, just writing a message here for anyone reading this.

Correct, this was to prevent duplicate container entities. We'll add the change you suggest and a logger to let us know if we encounter some container duplicates in the future. Nice suggestion!

2021-05-17 15:20 UTC, eXtremeX commented on src/steps/pods/index.ts
> +          const nodeUid = (await jobState.getData(
Great suggestion, we also had a chat about this. We'll add it shortly!

2021-05-19 16:47 UTC, kenanwarren commented on docs/jupiterone.md
> +| Kubernetes Node       | `kube_node`       | `Group`         |
We might want to make this map to a different entity class. From what I recall a `Node` is more in line with a `Host` in the current data model, but it's a bit fuzzy. A lot of managed providers do have what are called `NodePools` or `NodeGroups` where they group `Nodes` that have similar configurations (CPU/Memory/GPU) that might be closer to our `Group` entity class. This makes it easy to specify to the scheduler what pool you want your workload to run on. A concrete example of this is if I want to run some sort of ML modeling in the cluster I generally want to specify that it's going to be run on a node pool where I'm guaranteed to have access to a certain class of GPU. However, I'm pretty sure that's a custom CRD that most providers use and not built into the base api.

2021-05-19 16:50 UTC, kenanwarren commented on configs/cronjobCluster.yaml
> +kind: CronJob
For these configs we might want to specify these:
```
activeDeadlineSeconds: xxx <- This tells the scheduler to kill the job pod after the deadline
concurrencyPolicy: Forbid <- This tells the scheduler to not run another job pod if one is already running
```

2021-05-19 16:51 UTC, kenanwarren commented on configs/cronjobNamespace.yaml
> +kind: CronJob
For these configs we might want to specify these:
```
activeDeadlineSeconds: xxx <- This tells the scheduler to kill the job pod after the deadline
concurrencyPolicy: Forbid <- This tells the scheduler to not run another job pod if one is already running
```

2021-05-19 16:53 UTC, kenanwarren commented on configs/deploymentCluster.yml
> +      containers:
Might want to specify resource limits and requests, but the customer installing could also do that.

2021-05-19 16:53 UTC, kenanwarren commented on configs/deploymentNamespace.yml
> +      containers:
Same as Cluster deployment

2021-05-19 16:59 UTC, kenanwarren commented on src/steps/constants.ts
> +    _class: ['Configuration'],
fwiw most `ReplicaSets` are owned by `Deployments`. There aren't many cases where people deploying to k8s through the traditional yaml setup are declaring their own `ReplicaSets`, but that's also anecdotal. The only special workload resource I see used a lot is `StatefulSet` and that's for databases and such that need a stable backing storage.

2021-05-19 17:03 UTC, kenanwarren commented on src/steps/constants.ts
> +    _class: ['Group'],
I'd say they would be a host or workload. Generally they're grouped up by similar configurations (cpu/memory/gpu/etc) where you can specify to the scheduler which group/pool you want it to run on. This is pretty important for ML training or if you need specific type of operating systems (windows comes to mind).

2021-06-23 13:20 UTC, austinkelleher commented on configs/cronjobCluster.yaml
> +kind: CronJob
This is a great suggestion. We should definitely add these. It aligns more closely with the J1 scheduler. Perhaps we assign `activeDeadlineSeconds` a value of `10800` (3 hours)

2021-06-23 14:04 UTC, austinkelleher commented on src/steps/replica-sets/converters.ts
> +        'status.replicas': data.status?.replicas,
Considering that there are a large number of `status.` properties in this PR, I'm wondering if we should consider removing the `status.` prefix. What do you think @kenanwarren @aiwilliams?

2021-06-23 14:15 UTC, eXtremeX commented on src/steps/replica-sets/converters.ts
> +        'status.replicas': data.status?.replicas,
Just a quick comment on this before others join this conversation. Totally agree that many 'status.*' fields might look confusing, but the thing is - all the K8s resources fields are split into 3 sections - `metadata`, `spec`, and `status`.

`metadata` - name, uid, etc.
`spec` - the 'desired state of this resource' where the Kubernetes will do its best to try to create such a state and maintain it.
`status` - the actual state of this resource.

My only worry of not having 'status' prefix is maybe some of the 'desired spec values' will get mixed with the 'current resource values' and _might be_ hard/impossible to tell each other apart (unless we think of some naming convention like "actualReplicas" or "currentReplicas", "wantedReplicas" and so on).

Take for example these two ReplicaSet fields:

```
// Represents the desired number of replicas (pods)
replicas: data.spec?.replicas,
// Represents the actual/current number of replicas (pods)
'status.replicas': data.status?.replicas,
```
If a pod/node just died, the `status.replicas` # will be less than `spec.replicas` #, but some time later it should equal it (once K8s respawns them).

2021-06-24 17:19 UTC, kenanwarren commented on src/steps/replica-sets/converters.ts
> +        'status.replicas': data.status?.replicas,
I think we should keep them with the status prefix or make it a postfix like `replicasStatus`. Like Stefan mentioned the desired or optimistic state can be pretty different from the actual state in Kubernetes.

2021-06-24 17:53 UTC, austinkelleher commented on src/steps/replica-sets/converters.ts
> +        'status.replicas': data.status?.replicas,
Sounds good. We'll keep them as `status.` for now.

2021-06-24 17:54 UTC, austinkelleher approved these changes
Awesome job! Stefan is going to be working on some follow-up changes in separate PRs.

2021-06-24 17:54 UTC, merged

2021-06-24 18:01 UTC, aiwilliams commented on src/steps/replica-sets/converters.ts
> +        'status.replicas': data.status?.replicas,
I like the `status.` prefix. 👍